package com.senseup.drools.rules.firefighter

import com.senseup.drools.firefighter.domain.Person; 
import com.senseup.drools.firefighter.domain.Pet;
import com.senseup.drools.firefighter.domain.Firefighter;
import com.senseup.drools.firefighter.domain.Pet.PetType;


rule "Call a Cat when it is in a tree"
    when
        $p: Person($pet: pet, petCallCount == 0) 
        $cat: Pet(this == $pet, position == "on a limb", type == PetType.CAT)
    then
        System.out.println($p.getName()+": "+$cat.getName() + " come down!");
        modify($p){
            setPetCallCount($p.getPetCallCount()+1);
        }
end

rule "Call the fire department"
    when
        $p: Person($pet: pet, petCallCount > 0)
        $cat: Pet(this == $pet, position == "on a limb", type == PetType.CAT)
    then
       System.out.println($p.getName()+": Hello... Fire Department? My Cat is on a tree. Please help me.");
       Firefighter firefighter = new Firefighter("Fred");
       insert(firefighter);
end

rule "Firefighter gets the cat down"
    when
        $f: Firefighter()
        $p: Person($pet: pet, petCallCount > 0)
        $cat: Pet(this == $pet, position == "on a limb", type == PetType.CAT)
    then
        System.out.println("Firefighter " +$f.getName()+": I'm getting the cat down.");
        modify($cat){
            setPosition("on the street");
        }
        retract($f);

end

rule "Hello world!"
    when
        Person(petCallCount > 0)
    then
       System.out.println("Hello world!" );


end
